# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1b92770aaed1fe3b88093229099916e6b0eea845a4a28879d3926facc4d3a555698d2c618686b67000b1ee06c0b54e20a90c7da68dea3f02e01a397eecd3a9db

test:
  secret_key_base: f74eac5cbf8b7f894d189061f660ec95f511796a23534beb1bdfc577a942cf3a07f098424445272ddeca204431630776c13abf1c79e318c07e566ead3da92b4b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
